---
#Front end runner, will only build and deploy
stages:
  - install
  - build

install job:
  stage: install
  tags:
    - front-end
  script:
    - cd calculator
    - mkdir -p build
    - npm install

build and deploy job:
  stage: build
  tags:
    - front-end
  script:
    - npm run build
    - scp -r build mhasan@65.52.229.255:/var/www/html