---
#Front end runner, will only build and deploy
stages:
  - install
  - build
  - deploy

before_script:
  - cd calculator

install job:
  stage: install
  tags:
    - front-end
  script:
    - npm install
  cache:
    paths:
      - calculator/node_modules/

build job:
  stage: build
  tags:
    - front-end
  script:
    - npm run build
  artifacts:
    paths:
      - calculator/build/
  dependencies:
    - install job

deploy job:
  stage: deploy
  tags:
    - front-end
  script:
    - scp -r build mhasan@65.52.229.255:/var/www/html
  artifacts:
    paths:
      - calculator/build/
      - calculator/node_modules/
  dependencies:
    - build job