---
#Front end runner, will only build and deploy
stages:
  - build
  - deploy

before_script:
  - cd calculator
  - mkdir -p build

cache:
  paths:
    - node_modules


build job:
  stage: build
  tags:
    - front-end
  artifacts:
    paths:
      - build/
    when: always

  script:
    - npm install
    - npm run build
    - scp -r dest/build mhasan@65.52.229.255:/var/www/html

deploy job:
  stage: deploy
  tags:
    - runner
  script:
    - echo "test"