---
#Front end runner, will only build and deploy
stages:
  - build
  - deploy

before_script:
  - cd calculator
  - mkdir -p build
  - shopt -s globstar

build job:
  stage: build
  tags:
    - runner
  artifacts:
    paths:
      - build/*
      - node_modules/*
  script:
    - pwd
    - npm install
    - npm run build
    -  scp -r ./build mhasan@65.52.229.255:/var/www/html


deploy job:
  stage: deploy
  tags:
    - runner
  script:
    - echo "test"