---
#Front end runner, will only build and deploy
stages:
  - install
  - build
  - deploy

before_script:
  - cd calculator

install job:
  stage: install
  tags:
    - front-end
  script:
    - npm install

build job:
  stage: all
  tags:
    - front-end
  script:
    - npm run build

deploy job:
  stage: deploy
  tags:
    - front-end
  script:
    - scp -r build mhasan@65.52.229.255:/var/www/html