---
#Front end runner, will only build and deploy
stages:
  - build
  - deploy


before_script:
  - cd calculator

build job:
  stage: build
  tags:
    - front-end
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - calculator/build/

deploy job:
  stage: deploy
  tags:
    - front-end
  script:
    - scp -r build mhasan@65.52.229.255:/var/www/html
  dependencies:
    - build job