---
#Front end runner, will only build and deploy
stages:
  - build
  - deploy

before_script:
  - cd calculator
  - mkdir -p build
  - chmod +x runner.sh
cache:
  paths:
    - node_modules


build job:
  stage: build
  tags:
    - front-end
  artifacts:
    paths:
      - build/dest
    when: always

  script:
    - ./runner.sh


deploy job:
  stage: deploy
  tags:
    - runner
  script:
    - echo "test"