---
#Front end runner, will only build and deploy
stages:
  - build
  - deploy


build job:
  stage: build
  tags:
    - runner
  artifacts:
    paths:
      - build
  script:
    - cd calculator
    - npm run build

deploy job:
  stage: deploy
  tags:
    - runner
  script:
    - scp -r ./build mhasan@65.52.229.255:/var/www/html
